config/routes.rb
Rails.application.routes.draw do
  default_url_options :host => "localhost:3000"
  get 'password_resets/new'
  get 'password_resets/edit'
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  resource :sessions, only: [:new, :create, :destroy]
  resources :users, except: [:index, :destroy]
  resources :events do
    resource :rsvps, only: [:create, :destroy]
  end
  resources :password_resets, only: [:new, :create, :edit, :update]


  root 'home#index'

  # get '/pages/:page' => 'pages#show'
  get '/pages/about' => 'pages#about_us'
  get '/pages/partners' => 'pages#partners'
  get '/pages/waystogive' => 'pages#ways_to_give'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>United Way of Miami-Dade</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>


    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
    <%= javascript_pack_tag 'Calendar' %>
  </head>

  <!-- Bootstrap core JavaScript -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

  <body>
    <nav class="navbar navbar-expand-md navbar-dark" style="background-color: #000064">
      <a
        class="navbar-brand" href="<%= root_path %>"><%= image_tag "home/UW-logo.png", class: ["d-block", "w-75"]%>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a href="<%= root_path %>" class="nav-link">Home</a>
          </li>
          <li class="nav-item">
            <%= link_to "About Us", pages_about_path, :class => 'nav-link' %>
          </li>
          <li class="nav-item">
            <a href="<%= events_path %>" class="nav-link">Upcoming Events</a>
          </li>
          <li class="nav-item">
            <%= link_to "Ways to Give", pages_waystogive_path, :class => 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to "Partners", pages_partners_path, :class => 'nav-link' %>
            <!-- <%= link_to "Section", root_path, :class => "my-class", :id => "my-id" %>
            <a href="../pages/partners" class="nav-link">Partners</a> -->
          </li>
          <li>
            <a class="btn btn-danger" href="https://portal.unitedwaymiami.org/comm/SinglePageRegPledge.jsp?DA=6663454&SC=general" target="_blank" role="button">GIVE</a>
          </li>
        </ul>
        <ul class="nav navbar-nav flex-row justify-content-between ml-auto">
          <% if current_user %>
            <li class="m-1">
               <%= link_to "Logout", sessions_path, class: "btn btn-outline-secondary", method: :delete %>
            </li>
            <li class="m-1">
               <%= link_to "My Profile", user_path(current_user), class: "btn btn-outline-secondary" %>
            </li>
          <% else %>
            <li class="m-1">
              <%= link_to "Login", new_sessions_path, class: "btn btn-outline-secondary" %>
            </li>
            <li class="m-1">
              <%= link_to "Sign Up", new_user_path, class: "btn btn-outline-secondary" %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>


    <div class='container-fluid p-0'>
      <% flash.each do |name, msg| %>
        <div class='alert alert-<%= name %>'>
          <%= msg %>
        </div>
      <% end %>
      <%= yield %>
    </div>


      <!-- Footer -->
<footer class="page-footer font-small pt-4" style="background-color: #000064">

<div class="row m-2 align-center">
  <div class="col-md-4 text-white">
    <dt>United Way of Miami-Dade</dt>
      <dd>The Ansin Building</dd>
      <dd>3250 Southwest 3rd Avenue</dd>
      <dd>Miami, FL 33129-2712</dd>
      <dd>Phone: (305) 646–7000</dd>
    </dt>
  </div>

  <div class="col-md-4 text-white">
    <dt>United Way Center for Excellence in Early Education</dt>
      <dd>Royal Caribbean Building</dd>
      <dd>Batchelor Campus</dt>
      <dd>3250 Southwest 3rd Avenue</dd>
      <dd>Miami, FL 33129-2712</dd>
      <dd>Phone: (305) 631-7600</dd>
    </dt>
  </div>

  <div class="col-md-4 text-white">
    <dt>United Way Center for Financial Stability</dt>
      <dt>Main Branch</dt>
        <dd>11500 Northwest 12th Avenue</dd>
        <dd>Miami, FL 33168</dd>
        <dd>Phone: (305) 688-3551</dd>
        <dd>Fax: (305) 688-3556</dd>
      <dt>Florida City</dt>
        <dd>129 Southwest 5th Avenue</dd>
        <dd>Florida City, FL 33034</dd>
        <dd>Phone: (305) 688-3551</dd>
  </div>
</div>

        <div class="container">
          <ul class="list-unstyled list-inline text-center">
            <li class="list-inline-item">
              <a class="btn-floating btn-fb mx-1"
                href="https://www.facebook.com/UnitedWayMiami/" target="_blank">
                <i class="fab fa-facebook-f"></i>
              </a>
            </li>
            <li class="list-inline-item">
              <a class="btn-floating btn-tw mx-1"
                href="https://twitter.com/unitedwaymiami" target="_blank">
                <i class="fab fa-twitter"></i>
              </a>
            </li>
            <li class="list-inline-item">
              <a class="btn-floating btn-tw mx-1"
                href="https://www.instagram.com/unitedwaymiami/" target="_blank">
                <i class="fab fa-instagram"></i>
              </a>
            </li>
            <li class="list-inline-item">
              <a class="btn-floating btn-tw mx-1"
                href="https://www.linkedin.com/company/united-way-of-miami-dade/" target="_blank">
                <i class="fab fa-linkedin"></i>
              </a>
            </li>
            <li class="list-inline-item">
              <a class="btn-floating btn-tw mx-1"
                href="https://www.snapchat.com/add/unitedwaymiami" target="_blank">
                <i class="fab fa-snapchat"></i>
              </a>
            </li>
          </ul>
        </div>

        <div class="footer-copyright text-center text-white py-3">
          ©2018 United Way of Miami-Dade
        </div>

      </footer>
  </body>


</html>